import { Language, Translations, BlogPost } from './types';

export const UI_TRANSLATIONS: Record<Language, Translations> = {
  en: {
    searchPlaceholder: "Search the index...",
    currentIssue: "Current Issue",
    archives: "Archives",
    masthead: "About Us",
    readEntry: "READ ENTRY",
    backToIndex: "Back to Index",
    published: "Published",
    author: "Author",
    time: "Time",
    endOfEntry: "End of Entry",
    comments: "Comments",
    postComment: "Post a Comment",
    namePlaceholder: "Your Name",
    messagePlaceholder: "Your Thoughts...",
    submit: "Submit",
    noComments: "No comments yet. Be the first.",
    sortBy: "Sort by",
    newest: "Newest",
    oldest: "Oldest",
    relatedEntries: "Related Entries",
    classProject: "Assignment",
    course: "Course",
    creator: "Creator",
    aboutText: "The Index is a digital publication exploring the intersection of library science, technology, and culture. This project was created for LIS403 (Internet and Web Design) as an assignment to demonstrate modern information systems.",
    admin: "Admin",
    login: "Login",
    createPost: "Create New Entry",
  },
  ig: {
    searchPlaceholder: "Chọọ na ndepụta...",
    currentIssue: "Nke dị ugbu a",
    archives: "Ebe nchekwa",
    masthead: "Banyere Anyị",
    readEntry: "GỤỌ EDEMEDE",
    backToIndex: "Laghatarị na Ndepụta",
    published: "E bipụtara",
    author: "Odee",
    time: "Oge",
    endOfEntry: "Ọgwụgwụ Edemede",
    comments: "Nkwupụta",
    postComment: "Kpee Nkwupụta",
    namePlaceholder: "Aha Gị",
    messagePlaceholder: "Echiche Gị...",
    submit: "Nyefee",
    noComments: "O nwebeghị nkwupụta. Buru onye mbụ.",
    sortBy: "Hazi site na",
    newest: "Nke ọhụrụ",
    oldest: "Nke kacha ochie",
    relatedEntries: "Edemede ndị yiri ya",
    classProject: "Ọrụ Ụlọ",
    course: "Kọs",
    creator: "Onye Okike",
    aboutText: "The Index bụ akwụkwọ dijitalụ na-enyocha njikọ nke sayensị ọbá akwụkwọ, teknụzụ, na ọdịbendị. E mepụtara ọrụ a maka LIS403 (Internet and Web Design) dịka ọrụ ụlọ.",
    admin: "Admin",
    login: "Banye",
    createPost: "Mepụta Edemede Ọhụrụ",
  },
  yo: {
    searchPlaceholder: "Wá ninu atọka...",
    currentIssue: "Iwọn ti isiyi",
    archives: "Awọn ile ifipamọ",
    masthead: "Nipa Wa",
    readEntry: "KA AKỌSILẸ",
    backToIndex: "Pada si Atọka",
    published: "Ti a tẹjade",
    author: "Onkọwe",
    time: "Aago",
    endOfEntry: "Ipari Akọsilẹ",
    comments: "Awọn asọye",
    postComment: "Fi ọrọ ranṣẹ",
    namePlaceholder: "Orukọ Rẹ",
    messagePlaceholder: "Ero Rẹ...",
    submit: "Firanṣẹ",
    noComments: "Ko ti si awọn asọye. Jẹ ẹni akọkọ.",
    sortBy: "To lẹsẹẹsẹ",
    newest: "Titun julọ",
    oldest: "Ogbologbo julọ",
    relatedEntries: "Awọn nkan ti o jọra",
    classProject: "Iṣẹ Amurele",
    course: "Ẹkọ",
    creator: "Ẹlẹda",
    aboutText: "Atọka naa jẹ atẹjade oni-nọmba ti n ṣawari ikorita ti imọ-jinlẹ ile-ikawe, imọ-ẹrọ, ati aṣa. A ṣẹda iṣẹ yii fun LIS403 (Internet and Web Design) gẹgẹbi iṣẹ amurele.",
    admin: "Admin",
    login: "Wọle",
    createPost: "Ṣẹda Akọsilẹ Titun",
  },
  ha: {
    searchPlaceholder: "Bincika a fihirisa...",
    currentIssue: "Fitowar Yanzu",
    archives: "Taskoki",
    masthead: "Game da Mu",
    readEntry: "KARANTA RUBUTU",
    backToIndex: "Koma zuwa Fihirisa",
    published: "An wallafa",
    author: "Marubuci",
    time: "Lokaci",
    endOfEntry: "Karshen Rubutu",
    comments: "Sharhi",
    postComment: "Aika Sharhi",
    namePlaceholder: "Sunan Ka",
    messagePlaceholder: "Ra'ayinka...",
    submit: "Aika",
    noComments: "Babu sharhi tukuna. Kasance na farko.",
    sortBy: "Jeranta",
    newest: "Sabbi",
    oldest: "Tsoffi",
    relatedEntries: "Abubuwa masu alaƙa",
    classProject: "Aikin Gida",
    course: "Kwas",
    creator: "Mahalicci",
    aboutText: "The Index wallafe-wallafen dijitalụ ne da ke bincika tsaka-tsakin kimiyyar ɗakin karatu, fasaha, da al'adu. An kirkiro wannan aikin ne don LIS403 (Internet and Web Design) a matsayin aikin gida.",
    admin: "Admin",
    login: "Shiga",
    createPost: "Ƙirƙiri Sabon Rubutu",
  }
};

export const BLOG_POSTS: Record<Language, BlogPost[]> = {
  en: [],
  ig: [],
  yo: [],
  ha: []
};
